/*
    Crystal Space Windowing System: Theme Class
    Copyright (C) 2000 by Jerry Segler <jasegler@gerf.org>

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

#ifndef __CSTHEME_H__
#define __CSTHEME_H__

#include "csutil/hashmap.h"

class csThemeComponent;
class csComponent;
class csApp;

/// Possible window frame styles
enum csThemeFrameStyle
{
  csthfsNone,
  csthfsOblique,
  csthfsThickRect,
  csthfsThinRect,
  csthfsThin,
  csthfsTexture,
  /// This style is what a person should base CUSTOM styles off of.  i.e. csmyfsWacky = csthfsCustom+1, etc
  csthfsCustom
};

/**
 * The following commands are generated by theme changes.
 */
enum
{
  /**
   * Theme has change. (or multiple components in the theme)
   */
  cscmdThemeChange = 0x00000f00,
  /**
   * Theme Component has changed.
   */
  cscmdThemeComponentChange
};


/**
 * This class is the standard theme.  It is intended to be subclassed for custom themes.
 *<p>
 * Generally there should be only one object of this class.
 * However, you can specify a theme per component if you wish.
 */
class csTheme
{
protected:
  csApp * g_app;
  csHashMap * themeComponents;
  csHashKey HashName(char * name);

public:
  csTheme(csApp * napp);

  void DrawBorder(csComponent &comp,int FrameStyle,int &bw, int &bh,int li,int di);
  void GetBorderSize(csComponent &comp,int FrameStyle,int &bw, int &bh);

  void BroadcastThemeChange(csThemeComponent *tcomp);

  void AddThemeComponent(csThemeComponent * comp);
  csThemeComponent * GetThemeComponent(char * name);
  inline csApp * GetApp(){return g_app;};
};

class csThemeComponent
{
protected:
  char * name;
  csTheme * theme;

public:
  csThemeComponent(csTheme * ntheme);
  csTheme * GetTheme(void){return theme;};

  inline char *GetName() {return name;};
  inline void DrawBorder(csComponent &comp,int FrameStyle,int &bw, int &bh,int li,int di) \
    {theme->DrawBorder(comp,FrameStyle,bw,bh,li,di);};
  inline void GetBorderSize(csComponent &comp,int FrameStyle,int &bw, int &bh) \
    {theme->GetBorderSize(comp,FrameStyle,bw,bh);};

  void BroadcastThemeChange();
};

class csThemeButton : public csThemeComponent
{
protected:
  int BorderLightColor;
  int BorderDarkColor;
  int BackgroundColor;
  csPixmap * BorderTexture;

public:
  csThemeButton(csTheme * ntheme);
};

class csThemeWindow : public csThemeComponent
{
protected:
  int BorderWidth;
  int BorderHeight;
  int BorderLightColor;
  int BorderDarkColor;
  int BackgroundColor;
  csPixmap * BorderTexture;
  csPixmap *bmpClosen;
  csPixmap *bmpClosep;
  csPixmap *bmpHiden;
  csPixmap *bmpHidep;
  csPixmap *bmpMaximizen;
  csPixmap *bmpMaximizep;

public:
  csThemeWindow(csTheme * ntheme);

  int GetTitleBarHeight();
  int GetMenuHeight();
  int GetBorderLightColor(){return BorderLightColor;};
  void SetBorderLightColor(int Color){BorderLightColor = Color;};
  int GetBorderDarkColor(){return BorderDarkColor;};
  void SetBorderDarkColor(int Color){BorderDarkColor = Color;};
  int GetBackgroundColor(){return BackgroundColor;};
  void SetBackgroundColor(int Color){BackgroundColor = Color;};

  csComponent * GetCloseButton(csComponent *window);
  csComponent * GetHideButton(csComponent *window);
  csComponent * GetMaximizeButton(csComponent *window);
  csComponent * GetTitleBar(csComponent *window, char *iTitle);
};

#endif // __CSTHEME_H__
