Source: "..\..\include\*.h"; DestDir: "{#IncludeDir}"; Excludes: ".svn,Jamfile"; Flags: Touch
Source: "..\..\include\iengine\*"; DestDir: "{#IncludeDir}\iengine"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch
Source: "..\..\include\igeom\*"; DestDir: "{#IncludeDir}\igeom"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch
Source: "..\..\include\igraphic\*"; DestDir: "{#IncludeDir}\igraphic"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch
Source: "..\..\include\imap\*"; DestDir: "{#IncludeDir}\imap"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch
Source: "..\..\include\imesh\*"; DestDir: "{#IncludeDir}\imesh"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch
Source: "..\..\include\isndsys\*"; DestDir: "{#IncludeDir}\isndsys"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch
Source: "..\..\include\itexture\*"; DestDir: "{#IncludeDir}\itexture"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch
Source: "..\..\include\iutil\*"; DestDir: "{#IncludeDir}\iutil"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch
Source: "..\..\include\ivaria\*"; DestDir: "{#IncludeDir}\ivaria"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch
Source: "..\..\include\ivideo\*"; DestDir: "{#IncludeDir}\ivideo"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch

Source: "..\..\include\bindings\*"; DestDir: "{#IncludeDir}\bindings"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch
Source: "..\..\include\csgeom\*"; DestDir: "{#IncludeDir}\csgeom"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch
Source: "..\..\include\csgfx\*"; DestDir: "{#IncludeDir}\csgfx"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch
Source: "..\..\include\csplugincommon\*"; DestDir: "{#IncludeDir}\csplugincommon"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch
Source: "..\..\include\cstool\*"; DestDir: "{#IncludeDir}\cstool"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch

Source: "..\..\include\csutil\*"; DestDir: "{#IncludeDir}\csutil"; Excludes: ".svn,Jamfile"; Flags: Touch
Source: "..\..\include\csutil\macosx\*"; DestDir: "{#IncludeDir}\csutil\macosx"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch
Source: "..\..\include\csutil\unix\*"; DestDir: "{#IncludeDir}\csutil\unix"; Excludes: ".svn,Jamfile"; Flags: RecurseSubDirs Touch

Source: "..\..\include\csutil\win32\*.inc"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch
Source: "..\..\include\csutil\win32\callstack.h"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch
Source: "..\..\include\csutil\win32\csconfig.h"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch
Source: "..\..\include\csutil\win32\csosdefs.h"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch
Source: "..\..\include\csutil\win32\DbgHelpAPI.*"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch
Source: "..\..\include\csutil\win32\minidump.h"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch
Source: "..\..\include\csutil\win32\mmap.h"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch
Source: "..\..\include\csutil\win32\msvc_*.h"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch
Source: "..\..\include\csutil\win32\psdk-compat.h"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch
Source: "..\..\include\csutil\win32\registrycfg.h"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch
Source: "..\..\include\csutil\win32\sanity.inc"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch
Source: "..\..\include\csutil\win32\win32.h"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch
Source: "..\..\include\csutil\win32\wintools.h"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch

Source: "..\..\include\csutil\win32\z*.h"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch
Source: "..\..\include\csutil\win32\CEGUI*.h"; DestDir: "{#IncludeDir}\csutil\win32"; Flags: Touch
Source: "..\..\include\csutil\win32\elements\*"; DestDir: "{#IncludeDir}\csutil\win32\elements"; Flags: RecurseSubDirs Touch
Source: "..\..\include\csutil\win32\falagard\*"; DestDir: "{#IncludeDir}\csutil\win32\falagard"; Flags: RecurseSubDirs Touch
Source: "..\..\include\csutil\win32\XMLParserModules\*"; DestDir: "{#IncludeDir}\csutil\XMLParserModule"; Flags: RecurseSubDirs Touch
Source: "..\..\include\csutil\win32\cal3d\*"; DestDir: "{#IncludeDir}\csutil\win32\cal3d"; Flags: RecurseSubDirs Touch

