#ifndef __STUPID__TEST__
#define __STUPID__TEST__

#define STUPID_TEST			1
#define BOUNDARIES_OF_STUPID_TEST_U_MIN	0
#define BOUNDARIES_OF_STUPID_TEST_V_MIN	0
#define BOUNDARIES_OF_STUPID_TEST_U_MAX	-65536
#define BOUNDARIES_OF_STUPID_TEST_U_MAX	-65536

#endif
