/*  -*- Mode: C++; -*- */
/*
    Crystal Space 3D engine
    Copyright (C) 2000 by Jorrit Tyberghein

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

/*
 * Undo all defines set in 'blend.inc'.
 */

#undef PI_RM_BLEND
#undef PI_GM_BLEND
#undef PI_BM_BLEND
#undef PI_RS_GOUTEX
#undef PI_GS_GOUTEX
#undef PI_BS_GOUTEX
#undef PI_RM_GOUTEX
#undef PI_GM_GOUTEX
#undef PI_BM_GOUTEX
#undef PI_RBB
#undef PI_GBB
#undef PI_BBB
#undef PI_RBT_OFS
#undef PI_GBT_OFS
#undef PI_BBT_OFS

