BUILDDIR=$(HOME)/debian/crystal
DATE=$(shell date '+%Y%m%d')
VERSION=0.95
TAG=R0_95_001
MINOR=2
SITE=ftp://sunsite.dk/projects/crystal/
LEVELS=cs096/levels/demodata.zip \
	cs096/levels/dmburg.zip \
	cs096/levels/jngtest.zip \
	cs096/levels/maze.zip \
	cs096/levels/mazedex.zip \
	cs096/levels/newsky.zip \
	cs096/levels/room.zip \
	cs096/levels/sydney.zip \
	cs094/levels/demodata.zip \
	cs094/levels/castle.zip \
	cs094/levels/video.avi

default: start wget debcopy debbuild

start:
	@echo "Building Crystalspace-data-$(VERSION)  $(DATE)"

# To get file form ftp site
wget: $(BUILDDIR)/crystalspace-data-$(VERSION)/data $(BUILDDIR)/wget-stamp
$(BUILDDIR)/wget-stamp: $(LEVELS)
	echo "Wgetting files Done"
	#touch $(BUILDDIR)/wget-stamp

%.zip:
	@cd $(BUILDDIR)/crystalspace-data-$(VERSION)/data; wget -nc -nd -nH $(SITE)/$@
	cp ../../../homepage/img/$(shell basename $@ '.zip' ).jpg $(BUILDDIR)/crystalspace-data-$(VERSION)/data

%.avi:
	@cd $(BUILDDIR)/crystalspace-data-$(VERSION)/data; wget -nc -nd -nH $(SITE)/$@

debcopy:
	cd data ; find . | cpio -pdumvB $(BUILDDIR)/crystalspace-data-$(VERSION)/debian

debclean:
	cd $(BUILDDIR)/crystalspace-data-$(VERSION); fakeroot debian/rules clean
	
debconfigure:
	cd $(BUILDDIR)/crystalspace-data-$(VERSION); fakeroot debian/rules configure

debbinary:
	cd $(BUILDDIR)/crystalspace-data-$(VERSION);dch -v $(VERSION)-$(MINOR) Autobuild ; fakeroot debian/rules binary

debbuild:
	#cd $(BUILDDIR)/crystalspace-data-$(VERSION);dch -v $(VERSION)-$(MINOR) Autobuild ; debuild -us -uc
	cd $(BUILDDIR)/crystalspace-data-$(VERSION); debuild

$(BUILDDIR):
	mkdir -p $(BUILDDIR)

$(BUILDDIR)/crystalspace-data-$(VERSION)/data: $(BUILDDIR)/crystalspace-data-$(VERSION)
	-mkdir $(BUILDDIR)/crystalspace-data-$(VERSION)/data

$(BUILDDIR)/crystalspace-data-$(VERSION): $(BUILDDIR)
	-mkdir $(BUILDDIR)/crystalspace-data-$(VERSION)
clean:
	rm -f $(BUILDDIR)/*-stamp
