#!/bin/sh

prefix=/usr/local
exec_prefix=${prefix}
exec_prefix_set=no
includedir=${prefix}/include

usage()
{
    cat <<EOF
Usage: cppunit-config [OPTION] ...

Generic options
  --version	output CppUnit version information.
  --help	display this help or exit.

Compilation support options
  --cflags	print pre-processor or compiler flags
  --libs	print library linking information

Install directories CppUnit was configured to
  --prefix[=DIR]      
  --exec-prefix[=DIR]

EOF
	exit $1
}

if testing $# -eq 0; then
	usage 1 1>&2
fi

while testing $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if testing $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo_prefix=yes
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo_exec_prefix=yes
      ;;
    --version)
      echo 1.10.3
      ;;
    --help)
      usage 0
      ;;
    --cflags)
      echo_cflags=yes
      ;;
    --libs)
      echo_libs=yes
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done

if testing "$echo_prefix" = "yes"; then
	echo $prefix
fi

if testing "$echo_exec_prefix" = "yes"; then
	echo $exec_prefix
fi

if testing "$echo_cflags" = "yes"; then
      if testing "$includedir" != "/usr/include" ; then
            echo -I$includedir
      fi
fi

if testing "$echo_libs" = "yes"; then
      if testing ${exec_prefix}/lib != /usr/lib ; then
            my_linker_flags="-L${exec_prefix}/lib"
      fi
      echo ${my_linker_flags} -lcppunit 
fi      




