/*
    Copyright (C) 2004 by Jorrit Tyberghein
	      (C) 2004 by Frank Richter

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/	

#ifndef __CS_CSKEY_IDENTSTRS_H__
#define __CS_CSKEY_IDENTSTRS_H__

#include "cstool/identstrings.h"

CS_IDENT_STRING_LIST(KeyCodeNames)
  CS_IDENT_STRING(CSKEY_TAB)
  CS_IDENT_STRING(CSKEY_BACKSPACE)
  CS_IDENT_STRING(CSKEY_ENTER)
  CS_IDENT_STRING(CSKEY_ESC)
  CS_IDENT_STRING(CSKEY_SPACE)
  CS_IDENT_STRING(CSKEY_UP)
  CS_IDENT_STRING(CSKEY_DOWN)
  CS_IDENT_STRING(CSKEY_LEFT)
  CS_IDENT_STRING(CSKEY_RIGHT)
  CS_IDENT_STRING(CSKEY_PGUP)
  CS_IDENT_STRING(CSKEY_PGDN)
  CS_IDENT_STRING(CSKEY_HOME)
  CS_IDENT_STRING(CSKEY_END)
  CS_IDENT_STRING(CSKEY_INS)
  CS_IDENT_STRING(CSKEY_DEL)
  CS_IDENT_STRING(CSKEY_CONTEXT)
  CS_IDENT_STRING(CSKEY_PRINTSCREEN)
  CS_IDENT_STRING(CSKEY_PAUSE)
  CS_IDENT_STRING(CSKEY_F1)
  CS_IDENT_STRING(CSKEY_F2)
  CS_IDENT_STRING(CSKEY_F3)
  CS_IDENT_STRING(CSKEY_F4)
  CS_IDENT_STRING(CSKEY_F5)
  CS_IDENT_STRING(CSKEY_F6)
  CS_IDENT_STRING(CSKEY_F7)
  CS_IDENT_STRING(CSKEY_F8)
  CS_IDENT_STRING(CSKEY_F9)
  CS_IDENT_STRING(CSKEY_F10)
  CS_IDENT_STRING(CSKEY_F11)
  CS_IDENT_STRING(CSKEY_F12)
  CS_IDENT_STRING(CSKEY_SHIFT_LEFT)
  CS_IDENT_STRING(CSKEY_SHIFT_RIGHT)
  CS_IDENT_STRING(CSKEY_SHIFT)
  CS_IDENT_STRING(CSKEY_CTRL_LEFT)
  CS_IDENT_STRING(CSKEY_CTRL_RIGHT)
  CS_IDENT_STRING(CSKEY_CTRL)
  CS_IDENT_STRING(CSKEY_ALT_LEFT)
  CS_IDENT_STRING(CSKEY_ALT_RIGHT)
  CS_IDENT_STRING(CSKEY_ALT)
  CS_IDENT_STRING(CSKEY_CAPSLOCK)
  CS_IDENT_STRING(CSKEY_SCROLLLOCK)
  CS_IDENT_STRING(CSKEY_PADENTER)
  CS_IDENT_STRING(CSKEY_PAD0)
  CS_IDENT_STRING(CSKEY_PAD1)
  CS_IDENT_STRING(CSKEY_PAD2)
  CS_IDENT_STRING(CSKEY_PAD3)
  CS_IDENT_STRING(CSKEY_PAD4)
  CS_IDENT_STRING(CSKEY_PAD5)
  CS_IDENT_STRING(CSKEY_PAD6)
  CS_IDENT_STRING(CSKEY_PAD7)
  CS_IDENT_STRING(CSKEY_PAD8)
  CS_IDENT_STRING(CSKEY_PAD9)
  CS_IDENT_STRING(CSKEY_PADMULT)
  CS_IDENT_STRING(CSKEY_PADPLUS)
  CS_IDENT_STRING(CSKEY_PADMINUS)
  CS_IDENT_STRING(CSKEY_PADDECIMAL)
  CS_IDENT_STRING(CSKEY_PADDIV)
  CS_IDENT_STRING(CSKEY_PADNUM)
CS_IDENT_STRING_LIST_END(KeyCodeNames)

#endif // __CS_CSKEY_IDENTSTRS_H__
