#!/bin/sh

#
# mkverres
# make a windows version resource.
#

outfile=$1
description=$2

verfile=include/csver.h
vmajor=`sed -e '/#define[ 	][ 	]*CS_VERSION_MAJOR/!d' -e '/#define[ 	][ 	]*CS_VERSION_MAJOR/s/\(#define[ 	][ 	]*CS_VERSION_MAJOR[ 	][ 	]*"\)\([^\"]*\)"\(.*\)/\2/' < ${verfile}`
vminor=`sed -e '/#define[ 	][ 	]*CS_VERSION_MINOR/!d' -e '/#define[ 	][ 	]*CS_VERSION_MINOR/s/\(#define[ 	][ 	]*CS_VERSION_MINOR[ 	][ 	]*"\)\([^\"]*\)"\(.*\)/\2/' < ${verfile}`
vminor=`echo ${vminor} | sed -e s/[^[:digit:]]//g`

if [ "x$vminor" == "x" ]; then
	vminor=0
fi

echo > ${outfile}
echo '// This file is automatically generated' > ${outfile}
echo > ${outfile}
echo '#include "volatile.h"' >> ${outfile}
echo '#include "csver.h"' >> ${outfile}
echo >> ${outfile}
echo '#define CS_VERSION_W_DATE CS_VERSION " (" CS_RELEASE_DATE ")"' >> ${outfile}
echo >> ${outfile}
echo '1 VERSIONINFO' >> ${outfile}
echo 'FILEVERSION ' `echo ${vmajor} | sed -e s/[\.]/,/`','${vminor}',0' >> ${outfile}
echo '{' >> ${outfile}
echo '  BLOCK "StringFileInfo"' >> ${outfile}
echo '  {' >> ${outfile}
echo '    BLOCK "040904E4"' >> ${outfile}
echo '    {' >> ${outfile}
echo '      VALUE "ProductName", "CrystalSpace"' >> ${outfile}
echo '      VALUE "ProductVersion", CS_VERSION_W_DATE' >> ${outfile}
echo '      VALUE "FileVersion", CS_VERSION_NUMBER' >> ${outfile}
echo '      VALUE "LegalCopyright", "(c) 1998-2002 Jorrit Tyberghein and others"' >> ${outfile}
echo '      VALUE "FileDescription", "'${description}'"' >> ${outfile}
echo '#ifdef CS_DEBUG' >> ${outfile}
echo '      VALUE "Comments", "Debug build"' >> ${outfile}
echo '#else' >> ${outfile}
echo '      VALUE "Comments", "Release build"' >> ${outfile}
echo '#endif' >> ${outfile}
echo '      VALUE "WWW", "http://crystal.sourceforge.net/"' >> ${outfile}
echo '    }' >> ${outfile}
echo '  }' >> ${outfile}
echo '}' >> ${outfile}